# Do not modify this file!  It was generated by 'nixos-generate-config'
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
#
# This file uses auto-detection. On first boot, a systemd service will
# automatically generate the actual hardware configuration and replace this.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  # Auto-detection: This will be replaced by the actual hardware config
  # on first boot by the generate-hardware-config systemd service
}

