# Home Manager configuration for jens
{
  inputs,
  lib,
  config,
  pkgs,
  osConfig,
  ...
}: let
  # Source for the global ~/.claude/CLAUDE.md generated by Home Manager.
  machineAiSummary = ''
    # AGENTS.md

    This file provides guidance to coding agents working on this Nix-managed machine setup.

    ## Build & Test

    - After changing `.nix` files, run `nix fmt`.
    - After NixOS or Home Manager changes, run an appropriate `nixos-rebuild dry-build --flake .#<host>` before claiming success.
    - For permanent tools or config, edit Nix config under `/etc/nixos` and rebuild.
    - For temporary one-off tools, prefer `nix shell` or `, <cmd>` (`comma` is installed).
    - If work hits missing system dependencies, create a `flake.nix`/dev-shell setup and use `nix develop` instead of ad-hoc installers.

    ## Architecture Overview

    - OS: NixOS on Linux, current host is `${osConfig.networking.hostName}`
    - Config style: declarative NixOS flake + Home Manager
    - Shell: `zsh`
    - Desktop: KDE Plasma
    - Do not assume Debian/Fedora/Arch defaults here

    ## Conventions & Patterns

    - Do not suggest `apt`, `apt-get`, `dnf`, `yum`, `pacman`, or similar distro package managers.
    - Before proposing installs, first check whether a tool already exists with `command -v <tool>`.
    - Prefer reusable modules over large host-specific edits when possible.
    - Keep changes declarative and reproducible.
    - Prefer `fff` MCP for project file/content search when available.
    - Check `fff` availability with `opencode mcp list` or `command -v fff-mcp`.
    - Strong local CLI fallbacks already installed: `rg`, `fd`, `fzf`, `bat`, `eza`, `jq`, `tree`.

    ## Tools & Available Software

    - Nix: `nix`, `nixos-rebuild`, `nix fmt`, `nix-index`, `comma`, `nix-tree`, `nix-diff`, `deadnix`, `statix`, `sops`, `age`
    - AI/dev: `claude`, `opencode`, `droid`, `coderabbit`, `github-copilot-cli`, `gh`, `cliproxyapi`, `fff-mcp`
    - Languages/runtime: `node`, `bun`, `python3`, `uv`, `go`, `rust`, `dotnet`
    - Containers/devops: `docker`, `kubectl`, `k9s`, `lazydocker`
    - System/network: `fastfetch`, `btop`, `ncdu`, `rsync`, `curl`, `wget`, `nmap`, `tcpdump`, `dig`, `lsof`
    - Browser testing: Playwright browsers are preinstalled; avoid downloading them again unless needed
    - Desktop/apps often present: `google-chrome`, `claude-code`, `vesktop`, `telegram-desktop`, `obs-studio`, `gimp`, `inkscape`, `mpv`, `vlc`, `ktailctl`

    ## Useful Commands

    - `rebuild` => `sudo nixos-rebuild switch --flake /etc/nixos#${osConfig.networking.hostName}`
    - `update` => `nix flake update /etc/nixos`
    - `crr` => `coderabbit review --plain --type uncommitted`
    - `claude-team` starts Claude in tmux teammate mode
    - tmux helpers: `tmux-list`, `tmux-resume`, `tmux-kill`, `tmux-kill-all`
    - GPU mode helper: `/etc/nixos/switch-gpu-mode.sh <dedicated|hybrid|integrated>`

    ## Security

    - Secrets are managed with `sops`; never place secrets in plaintext config.
    - Check existing config before inventing new patterns or installers.
    - Prefer existing tools and repo conventions over adding new dependencies.

    ## Web Access Guidance

    - Prefer normal fetch/browser access first.
    - If a page is hard to parse and `firecrawl` exists, it can be used as a fallback.

    ## Custom Skills

    Declarative Claude Code skills live under `/etc/nixos/modules/home/claude-skills/` and are symlinked into `~/.claude/skills/<name>/SKILL.md` via `modules/home/base/shell.nix`. Two in-house skills worth knowing about:

    - **`context-handoff`** — write or update a `TODO.md` capturing session state (goal, done, in progress, next steps, discoveries, relevant files) before the context window fills up. **Trigger only on explicit ask** ("write a TODO.md", "do a handoff", "dump context to a file"). Merges into an existing `TODO.md` in place rather than overwriting.
    - **`delegate-plan`** — break a multi-task request into **waves** of file-disjoint tasks that run in parallel via `Agent` calls with `isolation: "worktree"`, separated by verify gates (`nix fmt` + `nixos-rebuild dry-build --flake .#<host>`). Default concurrency: 4 agents per wave. **Auto-triggers** on multi-file work, fan-outs, renames, rollouts — don't wait for the user to say "parallel".

    ## Agent Model

    - When spawning teammates or subagents, explicitly set `model: "claude-opus-4-6[1m]"` rather than relying on session defaults or inheritance.
  '';
in {
  imports = [
    # Base modules
    ../modules/home/base/shell.nix
    ../modules/home/base/programs.nix

    # Desktop modules
    ../modules/home/desktop/plasma/default.nix
    ../modules/home/desktop/konsole.nix
    ../modules/home/desktop/mangohud.nix

    # Feature modules
    ../modules/home/features/factory.nix

    # Specialized package modules
    ../modules/home/packages/gui/stremio.nix
    ../modules/home/packages/gui/media.nix
    ../modules/home/packages/gui/chrome.nix
    ../modules/home/packages/gui/tailscale.nix
    ../modules/home/packages/gui/gaming.nix
    ../modules/home/packages/gui/proton-run.nix
    ../modules/home/packages/gui/creative.nix
    ../modules/home/packages/cli/development.nix
    ../modules/home/packages/gui/communication.nix
    ../modules/home/packages/cli/base.nix
    ../modules/home/packages/gui/base.nix

    # Speech-to-text
    ../modules/home/features/whisper-ptt.nix

    # AI features
    ../modules/home/features/opencode.nix
    ../modules/home/features/remote-opencode.nix
    ../modules/home/features/cliproxyapi.nix
  ];

  myConfig.opencode = {
    enable = true;
    globalAgentsText = machineAiSummary;
    mcp = {
      fff = {
        type = "local";
        command = ["fff-mcp"];
        enabled = true;
      };
    };
    permission = {
      "*" = "allow";
    };
  };

  myConfig.remoteOpencode.enable = true;
  myConfig.cliproxyapi.enable = true;

  # Home Manager settings
  home = {
    username = "jens";
    homeDirectory = "/home/jens";
  };

  home.file.".claude/CLAUDE.md" = {
    text = machineAiSummary;
    force = true;
  };

  home.file.".factory/AGENTS.md" = {
    text = machineAiSummary;
    force = true;
  };

  # User-specific shell aliases
  programs.zsh.shellAliases = {
    # NixOS rebuild command for this host
    rebuild = "sudo nixos-rebuild switch --flake /etc/nixos#$(hostname)";
    update = "nix flake update /etc/nixos";
    # Custom aliases
    crr = "coderabbit review --plain --type uncommitted";
  };

  # User-specific git config
  programs.git.settings = {
    user.name = "jvz-devx";
    user.email = "jvz-devx@users.noreply.github.com";
    # Fix for "Bad owner or permissions on ~/.ssh/config" when running in namespaced environments (like Cursor)
    # This bypasses the SSH config file for Git operations and specifies the identity file directly.
    core.sshCommand = "ssh -i /home/jens/.ssh/id_ed25519 -o IdentitiesOnly=yes -F /dev/null";
  };

  # User-specific SSH config
  programs.ssh.matchBlocks = {
    "github.com" = {
      hostname = "github.com";
      user = "git";
      identityFile = "~/.ssh/id_ed25519";
      identitiesOnly = true;
      addKeysToAgent = "yes";
    };
    "proxmox" = {
      hostname = config.sops.placeholder.proxmox_host;
    };
  };

  # Enable home-manager itself
  programs.home-manager.enable = true;

  # Nicely reload system units when changing configs
  systemd.user.startServices = "sd-switch";

  # https://nixos.wiki/wiki/FAQ/When_do_I_update_stateVersion
  home.stateVersion = "26.05";
}
